apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
spec:
  selector: 
    app.kubernetes.io/instance: cd-jenkins
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: jenkins-public
    networking.gke.io/managed-certificates: jenkins.citwdd.net-certificate
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: jenkins-nodeport
    servicePort: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: jenkins.citwdd.net-certificate
spec:
  domains:
    - jenkins.citwdd.net
