apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dind
  template:
    metadata:
      labels:
        run: dind
    spec:
      containers:
        - env:
            - name: DOCKER_TLS_CERTDIR
          image: docker:dind
          name: dind
          ports:
            - containerPort: 2375
          securityContext:
            privileged: true
      restartPolicy: Always
