apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    run: jenkins
spec:
  ports:
    - name: "50000"
      port: 50000
      targetPort: 50000
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    run: jenkins
