apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jenkins
  template:
    metadata:
      labels:
        run: jenkins
    spec:
      containers:
        - env:
            - name: DOCKER_HOST
              value: tcp://dind:2375
            - name: JAVA_OPTS
              value: -Djava.awt.headless=true
          image: blayton784/jenkins-docker:latest
          name: jenkins
          ports:
            - containerPort: 50000
            - containerPort: 8080
      restartPolicy: Always
